---

- name: Query Azure VMs
  command: az vm list --resource-group {{ azure_resource_group }} --output json --show-details
  register: vm_list_cmd

- set_fact:
    vm_list: "{{ vm_list_cmd.stdout }}"

- name: Generate inventory
  template: src=inventory.j2 dest="{{playbook_dir}}/inventory"